### ISSUE TITLE
Virus Detected: Windows Defender

### ISSUE THREAD

**Issue by ilovefreesw** [DeMmAge/OnTopper#1]
**Describe the bug**

Windows Defender is flagging it as a severe infection. Can't even allow it from there. The setup file works though, just not the ZIP file.

**To Reproduce**

1. Download the ZIP from source forge.
2. Windows Defender will automatically block it.

**Expected behavior**

There shouldn't be any virus warnings.

https://www.virustotal.com/gui/file/92aedee17b926233f886d224efc98a84e2ef3aaa81e396496cb4457f8d71631c

![image](https://user-images.githubusercontent.com/77317006/138876097-1a190267-9a30-4177-83ad-7d8170cd58e9.png)

![image](https://user-images.githubusercontent.com/77317006/138876135-ee4c55b7-f791-40a1-a5a0-eed6ee0082de.png)

**Desktop (please complete the following information):**

 - OS: Windows 11
 - Browser Chrome
 - Version Latest

**Comment by silenzzz** [comment]
There is no malware in it. File is not signed, this is might be the reason anti viruses reacting like that. Installer created with [AdvancedInstaller](https://www.advancedinstaller.com). Why your windows defender blocks setup file - I don't know. A have latest win10 and kaspersky, there are not seeing malware in setup zip file.
